[project]
name = "followoo-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "alembic",
  "fastapi",
  "psycopg[binary]",
  "psycopg_pool",
  "pydantic-settings",
  "python-dotenv",
  "sentry-sdk",
  "slowapi",
  "sqlalchemy",
  "uvicorn",
]

[tool.ruff]
line-length = 88

[tool.mypy]
python_version = "3.13"
