export const ERROR_CODES = {
  INVALID_ZIP_FILE: "INVALID_ZIP_FILE",
  INVALID_INSTAGRAM_EXPORT: "INVALID_INSTAGRAM_EXPORT",
  UNSUPPORTED_EXPORT_FORMAT: "UNSUPPORTED_EXPORT_FORMAT",
  MISSING_REQUIRED_DATA: "MISSING_REQUIRED_DATA",
  RESULTS_NOT_AVAILABLE: "RESULTS_NOT_AVAILABLE",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type AppErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];