export const InstagramObjectArrayKeys = {
  FOLLOWING: "FOLLOWING",
  HIDE_STORIES_FROM: "HIDE_STORIES_FROM",
  FOLLOW_REQUESTS_SENT: "FOLLOW_REQUESTS_SENT",
  PERMANENT_FOLLOW_REQUESTS: "PERMANENT_FOLLOW_REQUESTS",
  UNFOLLOWED_USERS: "UNFOLLOWED_USERS",
  DISMISSED_SUGGESTED_USERS: "DISMISSED_SUGGESTED_USERS",
  RESTRICTED_USERS: "RESTRICTED_USERS",
  BLOCKED_USERS: "BLOCKED_USERS",
} as const;

export type InstagramObjectArrayKeys =
  typeof InstagramObjectArrayKeys[keyof typeof InstagramObjectArrayKeys];